= Viewing and Editing Mule Server Settings
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[WARNING]
Mule Management Console (MMC) was deprecated in December 2015. Its https://www.mulesoft.com/legal/versioning-back-support-policy#mule-management-console[End of Life] is July 15, 2019. For more information see the xref:release-notes::mule-runtime/mmc-migrator-tool.adoc[MMC Migrator Tool] or contact your Customer Success Manager to determine how you can migrate to xref:runtime-manager::index.adoc[Anypoint Runtime Manager].

Click the Settings tab to view the settings for the selected server. The pane displays the current server settings.

Clicking the *Edit Server Info* button allows you to modify information and settings for the server.

You can enter a new name for the server. You can also add this server to a group, by selecting a group from the pull-down list then clicking Add. You can also remove the server from a group it may already be in, by clicking the red X next to the group name. In addition, you can modify the agent URL.