= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mmc, requirements, installation

[WARNING]
Mule Management Console (MMC) was deprecated in December 2015. Its https://www.mulesoft.com/legal/versioning-back-support-policy#mule-management-console[End of Life] is July 15, 2019. For more information see the xref:release-notes::mule-runtime/mmc-migrator-tool.adoc[MMC Migrator Tool] or contact your Customer Success Manager to determine how you can migrate to xref:runtime-manager::index.adoc[Anypoint Runtime Manager].

Running Mule Management Console (MMC) on a separate server from the hardware that runs Mule Runtime is recommended. Hardware requirements are:

* 2GHz CPU
* 4 GB of RAM
* 10 GB of storage

== Software Requirements

MMC software requirements are:

* Oracle http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[Java 1.7] and Oracle http://www.oracle.com/technetwork/java/javase/overview/index.html[Java 1.8]
+
* Web Application Servers
+
** JBoss 6 or 6.1
** Apache Tomcat 6.x or 7.x
** WebSphere Application Server 7.0 and 8.0
** Oracle Weblogic 12.1.x (in MMC 3.7.3 and later)

* Operating Systems
+
MMC runs the operating systems supported by the supported web application servers.

*Browser
** Firefox (latest version)
** Chrome (latest version)
** Safari (latest version)
** Internet Explorer 10 or later
** Minimum screen resolution of 1024x768
+
* For Microsoft Dynamics GP connector use, http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8] or http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[JCE 7] unlimited strength jurisdiction policy files
+
If you do not use this connector, you do not need JCE. Install a JRE or JDK first, then install JCE.

== Compatible Databases for Persisting Data

* xref:persisting-mmc-data-to-oracle.adoc[Oracle]
* xref:persisting-mmc-data-to-postgresql.adoc[Postgres]
* xref:persisting-mmc-data-to-mysql.adoc[MySQL]
* xref:persisting-mmc-data-to-ms-sql-server.adoc[MS SQL Server]

== JVM Configuration

Run Mule Management Console as a web application deployed on a web container such as JBoss or Tomcat, *_not_ as a Mule application. Configure the following minimum web application server memory:

*  Heap: 2GB (3GB recommended)
*  Permanent Generation: 512MB