= Managing Mule High Availability (HA) Clusters
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

[WARNING]
Mule Management Console (MMC) was deprecated in December 2015. Its https://www.mulesoft.com/legal/versioning-back-support-policy#mule-management-console[End of Life] is July 15, 2019. For more information see the xref:release-notes::mule-runtime/mmc-migrator-tool.adoc[MMC Migrator Tool] or contact your Customer Success Manager to determine how you can migrate to xref:runtime-manager::index.adoc[Anypoint Runtime Manager].

The management console gives you the ability to manage server clusters. A cluster is a group of linked servers that work closely together. Once servers are added to a cluster, they function in many ways as if they were a single server.

[NOTE]
For an overview of clusters, including benefits and best practices, see xref:3.8@mule-runtime::mule-high-availability-ha-clusters.adoc[Mule High Availability HA Clusters].

You can perform the following cluster-related tasks with the console:

* xref:creating-or-disbanding-a-cluster.adoc[Create a cluster]
* xref:deploying-redeploying-or-undeploying-an-application-to-or-from-a-cluster.adoc[Deploy, redeploy, or undeploy an application to or from a cluster]
* xref:monitoring-a-cluster.adoc[Monitor a cluster, including its status]
* xref:creating-or-disbanding-a-cluster.adoc["Disband" or delete a cluster]

You can also create and manage a cluster programmatically using REST APIs.

Because clusters represent linked servers, you use functions available through the Servers tab to create and manage clusters. You also use functions available via the Applications tab to deploy applications to a cluster, in much the same way that you deploy applications to individual servers.

[NOTE]
====
*Ports Used for Clustering*

In order to configure a cluster, be sure to keep the following ports open:

* **port 5701**, which is used for communication between Mule and the cluster nodes
* *port 54327*, which is used for discovery of new cluster members

New cluster member discovery is performed using multicast, thus the multicast IP *224.2.2.3* must be enabled as well.
====